
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  fullName: 'fullName',
  password: 'password',
  phone: 'phone',
  status: 'status',
  address: 'address',
  isVerified: 'isVerified',
  image: 'image',
  googleId: 'googleId',
  emailVerified: 'emailVerified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  highestQualification: 'highestQualification',
  hsSchoolName: 'hsSchoolName',
  hsBoard: 'hsBoard',
  hsPassingYear: 'hsPassingYear',
  hsPercentage: 'hsPercentage',
  hssSchoolName: 'hssSchoolName',
  hssBoard: 'hssBoard',
  hssStream: 'hssStream',
  hssPassingYear: 'hssPassingYear',
  hssPercentage: 'hssPercentage',
  gradCollegeName: 'gradCollegeName',
  gradUniversity: 'gradUniversity',
  gradDegree: 'gradDegree',
  gradPassingYear: 'gradPassingYear',
  gradPercentage: 'gradPercentage',
  pgCollegeName: 'pgCollegeName',
  pgUniversity: 'pgUniversity',
  pgDegree: 'pgDegree',
  pgPassingYear: 'pgPassingYear',
  pgPercentage: 'pgPercentage',
  fathersName: 'fathersName',
  fathersPhone: 'fathersPhone',
  gender: 'gender',
  dateOfBirth: 'dateOfBirth',
  experienceYears: 'experienceYears',
  skills: 'skills',
  referredBy: 'referredBy',
  bankName: 'bankName',
  accountNumber: 'accountNumber',
  ifscCode: 'ifscCode',
  hsMarksheetUrl: 'hsMarksheetUrl',
  hssMarksheetUrl: 'hssMarksheetUrl',
  gradDegreeUrl: 'gradDegreeUrl',
  pgDegreeUrl: 'pgDegreeUrl'
};

exports.Prisma.OtpScalarFieldEnum = {
  id: 'id',
  email: 'email',
  code: 'code',
  expiresAt: 'expiresAt',
  verified: 'verified',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.PasswordResetScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  expiresAt: 'expiresAt',
  used: 'used',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  logo: 'logo',
  industry: 'industry',
  size: 'size',
  website: 'website',
  phone: 'phone',
  email: 'email',
  address: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  zipCode: 'zipCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  planName: 'planName',
  planAmount: 'planAmount',
  planStartDate: 'planStartDate',
  planExpiryDate: 'planExpiryDate',
  emailBalance: 'emailBalance',
  textBalance: 'textBalance',
  whatsappMarketingBalance: 'whatsappMarketingBalance',
  whatsappUtilityBalance: 'whatsappUtilityBalance',
  attendanceRules: 'attendanceRules',
  ownerId: 'ownerId'
};

exports.Prisma.WalletTransactionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  amount: 'amount',
  type: 'type',
  medium: 'medium',
  status: 'status',
  rechargeBy: 'rechargeBy',
  createdAt: 'createdAt'
};

exports.Prisma.OrganizationMemberScalarFieldEnum = {
  id: 'id',
  role: 'role',
  status: 'status',
  invitedAt: 'invitedAt',
  joinedAt: 'joinedAt',
  organizationId: 'organizationId',
  userId: 'userId'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  address: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  zipCode: 'zipCode',
  phone: 'phone',
  email: 'email',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  organizationId: 'organizationId'
};

exports.Prisma.UserBranchScalarFieldEnum = {
  id: 'id',
  role: 'role',
  isDefault: 'isDefault',
  employeeCode: 'employeeCode',
  designation: 'designation',
  department: 'department',
  joiningDate: 'joiningDate',
  salaryType: 'salaryType',
  salaryAmount: 'salaryAmount',
  isActive: 'isActive',
  appointmentLetterUrl: 'appointmentLetterUrl',
  joiningReportUrl: 'joiningReportUrl',
  userId: 'userId',
  branchId: 'branchId'
};

exports.Prisma.StudentScalarFieldEnum = {
  id: 'id',
  studentDisplayId: 'studentDisplayId',
  studentYear: 'studentYear',
  studentSequence: 'studentSequence',
  instituteCode: 'instituteCode',
  admissionDisplayId: 'admissionDisplayId',
  admissionYear: 'admissionYear',
  admissionSequence: 'admissionSequence',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  phone: 'phone',
  dateOfBirth: 'dateOfBirth',
  gender: 'gender',
  address: 'address',
  city: 'city',
  state: 'state',
  country: 'country',
  zipCode: 'zipCode',
  enrollmentNo: 'enrollmentNo',
  paymentStatus: 'paymentStatus',
  enrollmentDate: 'enrollmentDate',
  status: 'status',
  notes: 'notes',
  fathersName: 'fathersName',
  fathersPhone: 'fathersPhone',
  mothersName: 'mothersName',
  category: 'category',
  maritalStatus: 'maritalStatus',
  aadhaarNumber: 'aadhaarNumber',
  alternatePhone: 'alternatePhone',
  addressLine1: 'addressLine1',
  addressLine2: 'addressLine2',
  district: 'district',
  imageUrl: 'imageUrl',
  schoolCollege: 'schoolCollege',
  referredBy: 'referredBy',
  highestQualification: 'highestQualification',
  hsSchoolName: 'hsSchoolName',
  hsBoard: 'hsBoard',
  hsPassingYear: 'hsPassingYear',
  hsPercentage: 'hsPercentage',
  hssSchoolName: 'hssSchoolName',
  hssBoard: 'hssBoard',
  hssStream: 'hssStream',
  hssPassingYear: 'hssPassingYear',
  hssPercentage: 'hssPercentage',
  gradCollegeName: 'gradCollegeName',
  gradUniversity: 'gradUniversity',
  gradDegree: 'gradDegree',
  gradPassingYear: 'gradPassingYear',
  gradPercentage: 'gradPercentage',
  pgCollegeName: 'pgCollegeName',
  pgUniversity: 'pgUniversity',
  pgDegree: 'pgDegree',
  pgPassingYear: 'pgPassingYear',
  pgPercentage: 'pgPercentage',
  totalAmount: 'totalAmount',
  discountAmount: 'discountAmount',
  netPayableFee: 'netPayableFee',
  isPartPayment: 'isPartPayment',
  installmentPlan: 'installmentPlan',
  installmentMode: 'installmentMode',
  fullPayment: 'fullPayment',
  receivedBy: 'receivedBy',
  aadhaarCardUrl: 'aadhaarCardUrl',
  hsMarksheetUrl: 'hsMarksheetUrl',
  hssMarksheetUrl: 'hssMarksheetUrl',
  gradDegreeUrl: 'gradDegreeUrl',
  pgDegreeUrl: 'pgDegreeUrl',
  admissionFormUrl: 'admissionFormUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  courseId: 'courseId',
  batchId: 'batchId'
};

exports.Prisma.StudentCourseScalarFieldEnum = {
  id: 'id',
  studentId: 'studentId',
  courseId: 'courseId',
  status: 'status',
  totalFee: 'totalFee',
  discountAmount: 'discountAmount',
  netPayable: 'netPayable',
  joinedAt: 'joinedAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudentCourseBatchScalarFieldEnum = {
  id: 'id',
  studentCourseId: 'studentCourseId',
  batchId: 'batchId'
};

exports.Prisma.InstallmentScalarFieldEnum = {
  id: 'id',
  studentCourseId: 'studentCourseId',
  installmentNo: 'installmentNo',
  dueDate: 'dueDate',
  amount: 'amount',
  paidDate: 'paidDate',
  paidAmount: 'paidAmount',
  status: 'status',
  mode: 'mode',
  receiptNo: 'receiptNo',
  transactionId: 'transactionId',
  remarks: 'remarks',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CourseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  courseType: 'courseType',
  mode: 'mode',
  fee: 'fee',
  feeDescription: 'feeDescription',
  registrationFee: 'registrationFee',
  discountAllowed: 'discountAllowed',
  discountPercentage: 'discountPercentage',
  durationYears: 'durationYears',
  durationMonths: 'durationMonths',
  maxInstallments: 'maxInstallments',
  installmentAmounts: 'installmentAmounts',
  eligibility: 'eligibility',
  status: 'status',
  showInAdmissionForm: 'showInAdmissionForm',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  organizationId: 'organizationId'
};

exports.Prisma.BatchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  startTime: 'startTime',
  endTime: 'endTime',
  status: 'status',
  courseId: 'courseId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  courseId: 'courseId'
};

exports.Prisma.EnquiryScalarFieldEnum = {
  id: 'id',
  enquiryId: 'enquiryId',
  enquiryYear: 'enquiryYear',
  enquirySequence: 'enquirySequence',
  firstName: 'firstName',
  lastName: 'lastName',
  mobile: 'mobile',
  email: 'email',
  description: 'description',
  status: 'status',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  organizationId: 'organizationId',
  branchId: 'branchId',
  courseId: 'courseId'
};

exports.Prisma.ReceiptScalarFieldEnum = {
  id: 'id',
  receiptNo: 'receiptNo',
  receiptYear: 'receiptYear',
  receiptSequence: 'receiptSequence',
  amount: 'amount',
  date: 'date',
  mode: 'mode',
  transactionId: 'transactionId',
  remark: 'remark',
  studentId: 'studentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  published: 'published',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CounterScalarFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  date: 'date',
  status: 'status',
  type: 'type',
  remarks: 'remarks',
  studentId: 'studentId',
  employeeId: 'employeeId',
  branchId: 'branchId',
  batchId: 'batchId',
  organizationId: 'organizationId'
};

exports.Prisma.ModulePermissionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  organizationId: 'organizationId',
  module: 'module',
  canAccess: 'canAccess'
};

exports.Prisma.ReferrerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  type: 'type',
  status: 'status',
  defaultCommissionType: 'defaultCommissionType',
  defaultCommissionAmount: 'defaultCommissionAmount',
  organizationId: 'organizationId',
  branchId: 'branchId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReferralScalarFieldEnum = {
  id: 'id',
  referrerId: 'referrerId',
  studentId: 'studentId',
  status: 'status',
  rewardAmount: 'rewardAmount',
  rewardStatus: 'rewardStatus',
  paidDate: 'paidDate',
  payoutMode: 'payoutMode',
  payoutTransactionId: 'payoutTransactionId',
  payoutRemarks: 'payoutRemarks',
  notes: 'notes',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EducationBoardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.EducationUniversityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.EducationCollegeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.EducationSchoolScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.EducationDegreeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Otp: 'Otp',
  PasswordReset: 'PasswordReset',
  Organization: 'Organization',
  WalletTransaction: 'WalletTransaction',
  OrganizationMember: 'OrganizationMember',
  Branch: 'Branch',
  UserBranch: 'UserBranch',
  Student: 'Student',
  StudentCourse: 'StudentCourse',
  StudentCourseBatch: 'StudentCourseBatch',
  Installment: 'Installment',
  Course: 'Course',
  Batch: 'Batch',
  Subject: 'Subject',
  Enquiry: 'Enquiry',
  Receipt: 'Receipt',
  Post: 'Post',
  Counter: 'Counter',
  Attendance: 'Attendance',
  ModulePermission: 'ModulePermission',
  Referrer: 'Referrer',
  Referral: 'Referral',
  EducationBoard: 'EducationBoard',
  EducationUniversity: 'EducationUniversity',
  EducationCollege: 'EducationCollege',
  EducationSchool: 'EducationSchool',
  EducationDegree: 'EducationDegree'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
